### ISSUE TITLE
Need to ability add hotkeys

### ISSUE THREAD

**Issue by crantisz** [mrachinskiy/booltron#4] opened 2016-10-20 12:28 UTC
I want to add hotkeys to the operators. Of couse, a can do it in hotkey preferences, but not from context menus.

**Comment by mrachinskiy** [comment] 2016-10-20 12:40
So if you already have ability to add hotkeys for Booltron operators through the User Preferences, what is the issue here?

**Comment by mrachinskiy** [comment] 2016-10-20 13:03
The issue is that operator's id defined in add-on's context. To make add new shortcuts menu functionality available, it should be defined in object's context, so Blender would know in which context to create new shortcut.
But then operator's search popup will not show relation between these operators and Booltron. Basically it's code design and UX issue, not ideal in both cases.
I should think this through.

**Comment by crantisz** [comment] 2016-10-20 13:04
Becouse it isn't so easy. You need to know how to add hotkeys, You need to know name of operator. It is long and difficult
But from context menu it is fast and easy. You just click RMB, select "Add Shortcut" and add it.
But you can't:
![2016-10-20 15-57-55](https://cloud.githubusercontent.com/assets/1749968/19560774/7300050c-96de-11e6-9157-efb70fbd7cd5.png)

**Comment by mrachinskiy** [comment] 2016-10-20 15:30
Fixed by 65a36b9

**Closed by mrachinskiy** 2016-10-20 15:30 UTC
